### ISSUE TITLE
p2p with nat

### ISSUE THREAD

**Issue by grztofdev** [gbaranski/cryptogram#3]
Hi,
I have two machines, each one behind nat. 

Will they connect p2p? How?

**Comment by gbaranski** [comment]
> Hi,
> I have two machines, each one behind nat.
> 
> Will they connect p2p? How?

Hi, yes they will! That is possible because of rendezvous servers and DHT Discovery, if client B is already connected to rendezvous server, and client A connects to it, they can connect to themselves using [hole punching](https://en.m.wikipedia.org/wiki/Hole_punching_(networking)), that's similar to how BitTorrent protocol works.

**Comment by grztofdev** [comment]
So let's say we have two clients
Client A: public router ip address 1.2.3.4, private ip address behind NAT 192.168.0.120
Client B: public router ip address 2.4.6.8, private ip address behind NAT 192.168.0.121

How to connect these two clients using your chat? 
On client A:
```sh
go run main.go --dht --nick ClientA
```
On client B:
```sh
go run main.go --dht --nick ClientB
```

And where I have to type their ip addresses?

**Comment by gbaranski** [comment]
You don't need to, https://github.com/gbaranski/cryptogram/blob/e401f989eea4de81a3056721ff1ffa37a7ca010e/discovery/dht.go#L20 this shows how you're connected to rendezvous servers(aka bootstrap nodes), you can just run these two commands on clients in different networks, and they should connect after some time, in my case it was like 1-5 minutes, but there is open issue for that #2
